### ISSUE TITLE
Incorporar pasarela de Pago

### ISSUE THREAD

**Issue by candelarivetti** [MoneyFi/CureMDplus#13]
Agregar botón e integración a mercado pago y go cuotas. Que go cuotas explique las 3 o 4 cuotas sin interés. Por default ofrezca el pago anual con 10% de descuento y en cuotas (go cuotas) y sino en pago mensual sin descuento y sin cuotas (mercadopago)

**Comment by candelarivetti** [comment]
- Mercado pago con servicio de Guille
- GoCuotas: Unificar back con CureMD hacerlo con Nico

**Comment by candelarivetti** [comment]
**Mercado Pago**
Pagos recurrentes (total del importe dividido en meses)
- Guille finaliza script de Mercado Pago y comparte con Nahue y Lean
- Creamos productos en Mrcado Pago (x6 - x12 - En un pago)
- Nahue y Lean configuran el puerto

**GoCuotas**
Pagos recurrentes (total del importe dividido en meses)
- Nico compartió script}
- Nico da sporte para configurar

**Comment by NahuelCempellin** [comment]
Paginas de success y failure subidas
