### ISSUE TITLE
Desarrollar el formulario de Registro:

### ISSUE THREAD

**Issue by candelarivetti** [MoneyFi/CureMDplus#9]
Crear el componente Registro con el formulario para nuevos clientes.

- Nombre
- Apellido
- Correo Electrónico
- Teléfono
- Fecha de nacimiento
- Género (F/M/Prefiero no decirlo)
- CUIL

**Comment by LeandroNGarcia** [comment]
Integracion con el servicio de registro de la app hecha
Falta:
- CUIL(Agregar dato a la base)
- Permisos de CORS(Para realizar pruebas y verificar que el registro de usuarios sea exitoso)
